version: '3'

services:
  backend:
    build:
      context: ./capbackend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./capbackend:/app

  frontend:
    build:
      context: ./capfrontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./capfrontend:/app